---
title: "RISCC symposium 2021 survey data crunching/visualization"
date: "10/27/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(data.table)

dat = fread(here::here("2021_symposium_survey.csv"))

names(dat)

get_day_index = function(n, x)
{
  out = c()
  for(i in n)
    out = c(out, length(grep(pattern = as.character(i), x)))
  out = as.numeric(sapply(out, trimws))
  return(out)
}

get_entries = function(x)
{
  out = factor(sort(strsplit(paste0(x, collapse = ","), ",")[[1]]))
  out_t = table(out)
  out_t = out_t[order(out_t)]
  return(out_t)
}


wrap_text = function(x, max = 45, min=10)
{
  sub = sprintf('(.{%1$s,%2$s})(\\s|$)', min, max)
  return(gsub(sub, '\\1\n', x))
}


dates_1 = get_day_index(1:3, dat[, `Preferred dates [January 12-13-14]`])
dates_2 = get_day_index(1:3, dat[, `Preferred dates (choose as many as you would like): [January 19-20-21]`])
dates_3 = get_day_index(1:3, dat[, `Preferred dates (choose as many as you would like): [February 9-10-11]`])

mgt_table = dat[, get_entries(top_2_management)]
res_table = dat[, get_entries(top_3_research)]

par(las = 2, mar = c(3, 10, 3, 2))

barplot(mgt_table, names.arg = wrap_text(names(mgt_table)), horiz = TRUE)
barplot(res_table, names.arg = wrap_text(names(res_table)), horiz = TRUE)


n_top = 6
barplot_title_width = 20


bar_fill = rgb(0, 0.1, 0.2, 0.2)
bar_col = "steelblue"
bar_border = rgb(0, 0.1, 0)

```


# Scheduling

```{r scheduling, echo = FALSE, fig.align='center', fig.asp=1}
par(mar = c(2, 8, 2, 0))
par(mfrow = c(4, 1), las = 2, mar = c(3, 8, 3, 2))
barplot(
  dat[, table(scheduling_pref)[2:3]],
  main = "Scheduling Preference", 
  xlab = "Number of Responses", horiz = TRUE, las = 1)

b_ylm = c(0, 42)
{
  barplot(rev(dates_1), names.arg = rev(paste("Jan", 12:14)), xlim = b_ylm, horiz = TRUE, main = "January 12 - 14", col = bar_fill, border = bar_border); box()
  barplot(rev(dates_2), names.arg = rev(paste("Jan", 19:21)), xlim = b_ylm, horiz = TRUE, main = "January 19 - 21", col = bar_fill, border = bar_border); box()
  barplot(rev(dates_3), names.arg = rev(paste("Feb", 9:11)),  xlim = b_ylm, horiz = TRUE, main = "February 9 - 11", col = bar_fill, border = bar_border); box()
}

```



# Research Topics Top Responses

```{r research_topics, fig.width=12, fig.height=7, echo = FALSE}
par(las = 2, mar = c(3, barplot_title_width, 3, 2))
barplot(
  res_table[1:n_top],
  names.arg = wrap_text(names(res_table)[1:n_top]), 
  horiz = TRUE,
  col = bar_fill, border = bar_border)
```

# Management Topics Top Responses


```{r mgmt_topics, fig.width=12, fig.height=7, echo = FALSE}
par(las = 2, mar = c(3, barplot_title_width, 3, 2))
barplot(
  mgt_table[1:n_top], 
  names.arg = wrap_text(names(mgt_table)[1:n_top]), 
  horiz = TRUE, col = bar_fill, border = bar_border)
```

<!-- ## Other Topics Top Responses -->

<!-- ```{r, fig.width=20, fig.height=11, echo = FALSE} -->
<!-- n = 9 -->
<!-- par(mar = c(2, 20, 2, 0)) -->
<!-- barplot(other_topics_tab[1:n], horiz = TRUE, las = 1, -->
<!--         names.arg = gsub('(.{1,45})(\\s|$)', '\\1\n', names(other_topics_tab)[1:n])) -->
<!-- ``` -->


